### PR TITLE
Update Carthage support

### PR DESCRIPTION
**Pull request by li-bei**
- Update Swift version in .xcodeproj to 4.2
- Update deployment target for watchOS to 3.0 (Because RxSwift watchOS requires 3.0)

### CODE REVIEW

**Comment by li-bei** [comment]
Hi @icanzilb 

Do you have time to check this PR?

Thanks!

**Comment by icanzilb** [comment]
Is there anything else needed to make the new Carthage file work or just merging the PR?

**Comment by li-bei** [comment]
@icanzilb I think maybe we need a new release/tag to make this work.

**Comment by icanzilb** [comment]
@kylinroc could you give https://github.com/RxSwiftCommunity/RxRealm/releases/tag/0.7.7 a try please?

**Comment by li-bei** [comment]
@icanzilb It's ok now. 🎉

**Pull request merged**
