### PR TITLE
Add support for SwiftPM based dependency managers

### PR DESCRIPTION
**Pull request by pogramos**
This adds support for SwiftPM manifest based dependency managers. I tested using it with [Accio](https://github.com/JamitLabs/Accio) pointing out to my fork of the repo.

Currently, there's an open pull request [(#6127)](https://github.com/realm/realm-cocoa/pull/6127) on realm repo to add support for SPM based dependency managers too.

if/once it is integrated into the main repository, the dependency to RealmSwift will be changed to 

```swift
.package(url: "https://github.com/realm/realm-cocoa.git", .upToNextMajor(from: "3.15.0"))
```
to install it using Accio, just add the dependency on your `Package.swift`

### [dependencies]
```swift 
.package(url: "https://github.com/RxSwiftCommunity/RxRealm.git", .upToNextMajor(from: "1.0.0"))
```

### [targets]
```swift
.target(
    name: "AppName",
    dependencies: [
        ... [Assuming you already have Realm and RxSwift here] ...,
        "RxRealm"
    ]
)
```

### CODE REVIEW

**Comment by mariohahn** [comment]
+1

**Comment by freak4pc** [comment]
Hey there @pogramos - the Package.swift needs to be updated to 5.0 and use realm-cocoa's SPM configuration instead of a specific revision.

**Comment by pogramos** [comment]
Hello @freak4pc
I've made the proper changes to the `Package.swift` file!

**Review by freak4pc — APPROVED** [review]
LGTM! Thanks 😄

**Pull request merged**
