### PR TITLE
Fix Observable namespace for Swift5.9/XCode15 conflict

### LINKED ISSUE #199: Building with Xcode 15
Builds using Xcode 15 currently fail due to [the infamous `Observation.Observable` vs `RxSwift.Observable` issue](https://github.com/apple/swift/issues/67815).

PR with the workaround incoming.

### PR DESCRIPTION
**Pull request by arshiacont**
changed several `Observable` types to `RxSwift.Observable` to overcome XCode 15 conflict

#trivial  
fixes #199 and #201

### CODE REVIEW

**Comment by arshiacont** [comment]
@JoeMatt this PR is a no brainer and solves the XCode 15 issue... .

**Comment by erikmartens** [comment]
Any update on the progress or remaining requirements for this to be merged?

**Comment by arshiacont** [comment]
> Any update on the progress or remaining requirements for this to be merged?

A maintainer for the repo is needed here.. @JoeMatt @freak4pc ?

**Review by JoeMatt — APPROVED** [review]

**Comment by asn111** [comment]
I am also unable to load my project and these are the issues it displays.
Any idea how to fix these?
Thanks 🙏 

Screenshot 2023-09-27 at 8 37 05 PM

**Comment by arshiacont** [comment]
@JoeMatt Possible to release a hotfix 5.0.6? (thanks for approval)

**Comment by JoeMatt** [comment]
Tonight. Finally have a break on the rain around here.

**Comment by yspreen** [comment]
wanna add the iOS 12 minimum version bump too?

**Comment by hoc081098** [comment]
Please publish it 💯

**Comment by erikmartens** [comment]
Until either @JoeMatt or @freak4pc merge this and update the PodSpec all of y'all (@asn111 ?) who are using CocoaPods and have updated to macOS Sonoma, which prevents you from using Xcode 14, can just point to the branch of this fix in the `Podfile` by using `pod 'RxRealm', :git => 'https://github.com/arshiacont/RxRealm.git', :branch => 'bugfix/xcode15', :commit => 'ec4ac63'`

I'm able to build and run my app fine on macOS 14 with Xcode 15.

**Comment by imvityalee** [comment]
Can you merge this ? @JoeMatt

**Comment by rynecheow** [comment]
@arshiacont Able to fix the pipeline before we merge this?

**Comment by arshiacont** [comment]
> @arshiacont Able to fix the pipeline before we merge this?

@rynecheow the pipeline errors seems to be a dependency issue and independent of any PR... . 

@JoeMatt you kindly approved the changes last week amid rain! :) If you could merge to the main branch it'll avoid people to point to my Fork (which is probably not right!). Getting an SPM/Pod release would be best.

**Comment by diegothucao** [comment]
Hi team, could you check to release this ?

**Comment by s14228so** [comment]
@JoeMatt 
Please publish it🙇🙏

**Comment by Tom0430** [comment]
@JoeMatt Possible to release?

**Comment by ibukiblue** [comment]
@JoeMatt 
Is there some problem that makes it impossible to release?🫠

**Comment by freak4pc** [comment]
Stop commenting and tagging every 15 minutes, this is seriously disrespectful. This project isn't maintained as was noted before and people are volunteering their free time to try and assist. If you're under a time crunch just direct your project to the specific tag / commit and move on until this is resolved.

**Comment by arshiacont** [comment]
Just updated Cocoapod dependency in the workflow hoping this will pass the checks and we can have a smooth release. Pending workflow approval and final check, we might want to modify other dependencies... .

**Comment by yspreen** [comment]
Is the iOS 11.0 vs 12.0 dependency issue fixed as well? That's causing some build issues for us. We had to bump the minimum manually

**Comment by arshiacont** [comment]
> Is the iOS 11.0 vs 12.0 dependency issue fixed as well? That's causing some build issues for us. We had to bump the minimum manually

@yspreen I would create a separate issue on that. Focusing on getting this one over with.

**Comment by freak4pc** [comment]
the tl;dr here is that - if someone wants to take over and maintain this project, we're happy to add a second owner to take care of it. If not, it might take a bit of time due to time (and war) constraints.

**Comment by imvityalee** [comment]
> the tl;dr here is that - if someone wants to take over and maintain this project, we're happy to add a second owner to take care of it. If not, it might take a bit of time due to time (and war) constraints.

It would be great if you will add someone as an owner, I can help with this stuff. You can add me

**Comment by rynecheow** [comment]
I can help to approve this and merge, provided the pipeline is green :) Able to help fixing the pipeline error please? Seems like a Cocoapods iOS demo issue

**Comment by arshiacont** [comment]
> I can help to approve this and merge, provided the pipeline is green :) Able to help fixing the pipeline error please? Seems like a Cocoapods iOS demo issue

Just a hint: There is apparently a problem with the version of the dependency `activesupport` used here... I had this on my local machine which was solved by just fixing the version to what was required by Cocoapods... but I did not dig into how we can solve it on this project.

**Comment by lihao6485** [comment]
@arshiacont yes you are right, it is related to the latest version of `activesupport` (7.1.0)
https://github.com/CocoaPods/CocoaPods/issues/12081

as a temporary workaround could we try to add `gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'` into gemfile in this PR?

**Comment by arshiacont** [comment]
@lihao6485 @rynecheow just moved Cocoapod dependency to 1.14.0 (released yesterday) that addresses the ActiveSupport crash. Hopefully this will fix the workflow for this PR.

**Comment by lihao6485** [comment]
@arshiacont I have fixed the CI build issue, could you try to merge this PR in your branch and run the CI again?
https://github.com/arshiacont/RxRealm/pull/1

**Comment by arshiacont** [comment]
> @arshiacont I have fixed the CI build issue, could you try to merge this PR in your branch and run the CI again?
> 
> https://github.com/arshiacont/RxRealm/pull/1

Done! Awaiting approval

**Comment by fpedro23** [comment]
Thanks for merging!

**Pull request merged**
