### PR TITLE
Update for Xcode 14 build

### PR DESCRIPTION
**Pull request by marcuswu0814**
According to [this PR](https://github.com/realm/realm-swift/pull/7829), the Realm version should update to support build with Xcode 14. 🙏

### CODE REVIEW

**Comment by marcuswu0814** [comment]
Hi @JoeMatt, could you please help to review and merge this PR? 😀

**Comment by JoeMatt** [comment]
This isn't a blocker since you can just "package update" and should pull the latest version of RxSwift to fix this issue.
Tested myself on a few projects and everything should work as-is with XCode 14 after a dependency update.

That being said, I'll approve this PR but not in a rush to make a release based on it since fundamietally it doesn't change the version locking restrictions since the latest RxRealm is a minor version, not a major.

**Review by JoeMatt — APPROVED** [review]

**Review by JoeMatt — APPROVED** [review]

**Comment by JoeMatt** [comment]
merged in [2cefb02](https://github.com/RxSwiftCommunity/RxRealm/commit/2cefb02375887fa80b915f7079ea700388227a51)

**Comment by marcuswu0814** [comment]
Hi @JoeMatt, really thanks for your tip! ❤️ Finally I run `pod update Realm RealmSwift RxRealm` and the Realm version can be updated successfully. 🎉 BTW, I faced problem by running `pod update RealmSwift` and it cause dependency problem previously. 😅

**Comment by JoeMatt** [comment]
Yeah previously it may have but since upstream updates requires weren’t version locked in our pod file or package.swift, they should both work now on master with RxSwift package update.

Joe Mattiello
________________________________

**Pull request merged**
