### PR TITLE
Swift 3.0 support

### PR DESCRIPTION
**Pull request by ewerx**

### CODE REVIEW

**Comment by nikriek** [comment]
Hey, is there any progress on this PR? I would love to use RxRealm with Swift 3 😄

**Comment by icanzilb** [comment]
coming back from a long trip in NYC this weekend and this is on my todo for next week, thanks for your patience :)

**Comment by nikriek** [comment]
Nice 👍 I can also give support if needed

**Comment by ewerx** [comment]
I believe the only thing that needs to be fixed is the podspec dependencies. 
For both RxSwift and realm-cocoa the `master` branch is needed for Swift 3 compatibility, but a podspec dependency can only point to a release / version.

**Comment by icanzilb** [comment]
Looking into the swift3 version ...

**Comment by sendyhalim** [comment]
I just submit a pull request to https://github.com/ewerx/RxRealm/pull/1, hopefully it's working fine 🍡

**Comment by icanzilb** [comment]
After discussed with kzaher it seems like the final syntax needs to wait a bit until the final RxSwift 3.0 version

**Comment by sendyhalim** [comment]
@icanzilb makes sense, okay then let's wait 😄

**Comment by icanzilb** [comment]
okay pushed what I have locally in kind of a pre-release (still depends on a beta version of RxSwift) so let's see if there's any feedback about it

**Pull request closed without merging**
